"""baseline schema

Revision ID: 0001
Revises: 
Create Date: 2026-07-05 02:27:58.236681
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.String(), nullable=False),
    sa.Column('approval_type', sa.String(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('approver_role', sa.String(), nullable=False),
    sa.Column('approver_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_requests_approval_type'), ['approval_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_status'), ['status'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actionType', sa.String(), nullable=False),
    sa.Column('dataset', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('impact_pct', sa.Float(), nullable=True),
    sa.Column('affected_categories_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_start_date'), ['start_date'], unique=False)

    op.create_table('demand_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('target_demand', sa.Float(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('hierarchy_levels', sa.JSON(), nullable=True),
    sa.Column('exogenous_variables', sa.JSON(), nullable=True),
    sa.Column('planner_id', sa.String(), nullable=True),
    sa.Column('dataset_version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('demand_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demand_records_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_demand_records_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_demand_records_dataset_version'), ['dataset_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_demand_records_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_demand_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_demand_records_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_demand_records_planner_id'), ['planner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_demand_records_sku'), ['sku'], unique=False)

    op.create_table('demand_sensing_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('actual_sales', sa.Float(), nullable=False),
    sa.Column('dataset_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('demand_sensing_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demand_sensing_signals_dataset_version'), ['dataset_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_demand_sensing_signals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_demand_sensing_signals_sku'), ['sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_demand_sensing_signals_timestamp'), ['timestamp'], unique=False)

    op.create_table('forecast_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('forecast_demand', sa.Float(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('ensemble_strategy', sa.String(), nullable=True),
    sa.Column('horizon', sa.Integer(), nullable=False),
    sa.Column('dataset_version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forecast_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecast_results_dataset_version'), ['dataset_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecast_results_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecast_results_ensemble_strategy'), ['ensemble_strategy'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecast_results_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecast_results_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecast_results_sku'), ['sku'], unique=False)

    op.create_table('sku_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('asp', sa.Float(), nullable=False),
    sa.Column('lead_time', sa.Integer(), nullable=False),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sku_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sku_master_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_sku_master_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sku_master_sku'), ['sku'], unique=True)
        batch_op.create_index(batch_op.f('ix_sku_master_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sku_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sku_master_status'))
        batch_op.drop_index(batch_op.f('ix_sku_master_sku'))
        batch_op.drop_index(batch_op.f('ix_sku_master_id'))
        batch_op.drop_index(batch_op.f('ix_sku_master_category'))

    op.drop_table('sku_master')
    with op.batch_alter_table('forecast_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecast_results_sku'))
        batch_op.drop_index(batch_op.f('ix_forecast_results_model_name'))
        batch_op.drop_index(batch_op.f('ix_forecast_results_id'))
        batch_op.drop_index(batch_op.f('ix_forecast_results_ensemble_strategy'))
        batch_op.drop_index(batch_op.f('ix_forecast_results_date'))
        batch_op.drop_index(batch_op.f('ix_forecast_results_dataset_version'))

    op.drop_table('forecast_results')
    with op.batch_alter_table('demand_sensing_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demand_sensing_signals_timestamp'))
        batch_op.drop_index(batch_op.f('ix_demand_sensing_signals_sku'))
        batch_op.drop_index(batch_op.f('ix_demand_sensing_signals_id'))
        batch_op.drop_index(batch_op.f('ix_demand_sensing_signals_dataset_version'))

    op.drop_table('demand_sensing_signals')
    with op.batch_alter_table('demand_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demand_records_sku'))
        batch_op.drop_index(batch_op.f('ix_demand_records_planner_id'))
        batch_op.drop_index(batch_op.f('ix_demand_records_location'))
        batch_op.drop_index(batch_op.f('ix_demand_records_id'))
        batch_op.drop_index(batch_op.f('ix_demand_records_date'))
        batch_op.drop_index(batch_op.f('ix_demand_records_dataset_version'))
        batch_op.drop_index(batch_op.f('ix_demand_records_channel'))
        batch_op.drop_index(batch_op.f('ix_demand_records_category'))

    op.drop_table('demand_records')
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_events_start_date'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_event_type'))

    op.drop_table('calendar_events')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_requests_status'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_requester_id'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_id'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_approval_type'))

    op.drop_table('approval_requests')
    # ### end Alembic commands ###
