-- Planora AI — PostgreSQL first-boot initialization.
--
-- This runs ONCE when the postgres container initializes an empty data volume,
-- BEFORE the application or Alembic have connected. It must therefore contain only
-- statements that are valid against an empty database (no tables exist yet).
--
-- All schema — tables, indexes, constraints, views — is owned by Alembic migrations
-- (`alembic upgrade head`), NOT by this file. Do not add CREATE TABLE/INDEX/VIEW here;
-- they would fail at first-boot because the referenced tables do not exist yet.
--
-- The application connects as POSTGRES_USER (the database owner), so no additional
-- table-level GRANTs are required. A dedicated least-privilege application role is a
-- Phase 2 (security-hardening) item.

-- Intentionally minimal. Add database-level prerequisites (e.g. extensions) here only
-- if a migration later depends on them.
